### ISSUE TITLE
I am submitting a download request

### ISSUE THREAD

**Issue by Botspot** [oureveryday/WallpaperEngineWorkshopDownloader#1]
Hello, I have not been able to get this working.

Here is a screenshot.
![Screenshot from 2024-07-09 01-30-29](https://github.com/oureveryday/WallpaperEngineWorkshopDownloader/assets/54716352/ba8e6417-cd1a-4676-9901-5ae434aaf9bb)

Is the program from your Releases page still working? It is possible that the Steam accounts were all banned. I am not sure.
Can you try downloading this file to see if it works? https://steamcommunity.com/sharedfiles/filedetails/?id=2996865921

**Comment by oureveryday** [comment]
You are using it on wine?
This is a network issue to steam servers.
You should try steam connection again.

**Comment by Botspot** [comment]
Yes, I am using Wine.
I think I installed .NET 8 correctly, but could you check if that wallpaper can be downloaded?

**Comment by Botspot** [comment]
Would you be willing to download that wallpaper and send it to me? I am tired of trying to get this to work on my operating system.

**Comment by oureveryday** [comment]
Do you have any contact method such as discord or telegram?

**Comment by Botspot** [comment]
> Do you have any contact method such as discord or telegram?

Yes. Send a friend request to `botspot.` (with the `.` character at the end)

**Comment by oureveryday** [comment]
Added, please accept request.
