### ISSUE TITLE
App 431960 was not completely downloaded

### ISSUE THREAD

**Issue by leonardo-oul** [oureveryday/WallpaperEngineWorkshopDownloader#10]
选择完包含/projects/myprojects路径后执行下载出现提示App未安装
控制台输出内容：
----------正在下载 3342703486--------
Connecting to Steam3... Done!
Logging 'ruiiixx' into Steam3...
 Done!
Using Steam3 suggested CellID: 198
Got 24 licenses for account!
Got AppInfo for 431960
Got depot key for 431960 result: OK
Processing depot 431960
Downloading depot manifest... Got manifest request code for 431960 266457897950858871 result: 9601846168450579132
App 431960 was not completely downloaded.
A task was canceled.
Disconnected from Steam
-------------下载完成-----------

**Comment by oureveryday** [comment]
这个是DepotDownloader的问题，目前还未确定原因，正在解决中。
目前要下载可以使用国外的CDN。

**Comment by oureveryday** [comment]
[1.0.3](https://github.com/oureveryday/WallpaperEngineWorkshopDownloader/releases/tag/1.0.3) 已修复
