### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by evoSTARZ** [oureveryday/WallpaperEngineWorkshopDownloader#12]
it keeps saying (Error: Save location is not exist.)

**Comment by oureveryday** [comment]
You have to select the root directory of the wallpaper engine

**Comment by evoSTARZ** [comment]
how ?

**Comment by evoSTARZ** [comment]
i selected it (Invaild save location: Selected directory does not contain \projects\myprojects)

**Comment by oureveryday** [comment]
Screenshot your selected folder's content

**Comment by evoSTARZ** [comment]
![image](https://github.com/user-attachments/assets/2663a0a8-eef8-4eaf-9355-42486623925e)

**Comment by oureveryday** [comment]
> ![image](https://github.com/user-attachments/assets/2663a0a8-eef8-4eaf-9355-42486623925e)

i said you have to set the root folder which contains that folders.

**Comment by evoSTARZ** [comment]
how ?

**Comment by oureveryday** [comment]
> how ?

figure it out yourself
