### ISSUE TITLE
Error: Save location is not exist. Invaild save location: Selected directory does not contain \projects\myprojects

### ISSUE THREAD

**Issue by ZaidRocket** [oureveryday/WallpaperEngineWorkshopDownloader#13]
Error: Save location is not exist.
Invaild save location: Selected directory does not contain \projects\myprojects 
is the message i get when i go to the steam wallpaper folder projects/my projects. If your software is only meant to support non hacked steam wallpaper then its my fault and you should completely ignore this

Thank You

**Comment by oureveryday** [comment]
you have to select the root folder of wallpaper engine which contains wallpaper64.exe
