### ISSUE TITLE
[WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by vedantakbari** [oureveryday/WallpaperEngineWorkshopDownloader#14]
I saw the other two issue but i dont know what to do. I have basically have no exp w coding

**Comment by oureveryday** [comment]
You have to put depotdownloadermod folder beside the program

**Comment by vedantakbari** [comment]
what do you mean by beside? sorry if my english sounds bad, im not good at it

**Comment by oureveryday** [comment]
Extract the release.rar totally instead of running it directly.
If you don't understand you shouldn't use this.

**Comment by vedantakbari** [comment]
alright thanks, should i extract it in the downloader root or the wallpaper engine route

**Comment by oureveryday** [comment]
anywhere you want

**Comment by vedantakbari** [comment]
hello sir, i have extracted it but i still seem to get an error

**Comment by oureveryday** [comment]
screenshot your program folder and error

**Comment by vedantakbari** [comment]
thanks for helping, you have real good patience, i appreciate it
![Screenshot 2024-12-27 235718](https://github.com/user-attachments/assets/0cc786e5-bc9d-4342-8c41-ef7b6596626a)

**Comment by oureveryday** [comment]
ok so you have to use one from release section, which contains depotdownloadermod.

**Comment by vedantakbari** [comment]
thanks a lot
