### ISSUE TITLE
Save Location

### ISSUE THREAD

**Issue by Nrnr007** [oureveryday/WallpaperEngineWorkshopDownloader#2]
I choose the project\myprojects and it still says that it is invalid
Here is a screenshot for that 
![Screenshot (7)](https://github.com/oureveryday/WallpaperEngineWorkshopDownloader/assets/122174520/3f41abda-c395-4844-bed4-cfeca5ba6a1c)
![Screenshot (8)](https://github.com/oureveryday/WallpaperEngineWorkshopDownloader/assets/122174520/00d6aa42-0af8-4010-a64e-24c02194ef55)

**Comment by oureveryday** [comment]
You should choose the wallpaper engine root folder which contains the projects folder.

**Comment by Nrnr007** [comment]
Thanks for the great project
