### ISSUE TITLE
why bro leaking passwords tho

### ISSUE THREAD

**Issue by anhwaivo** [oureveryday/WallpaperEngineWorkshopDownloader#3]
im just dumb

**Comment by oureveryday** [comment]
These accounts are necessary to download the wallpaper. And these accounts are shared accounts collected from Internet.

Btw the password is encrypted in some way, you need to have at least little knowledge to decrypt it.

**Comment by anhwaivo** [comment]
> These accounts are necessary to download the wallpaper. And these accounts are shared accounts collected from Internet.
> 
> Btw the password is encrypted in some way, you need to have at least little knowledge to decrypt it.

oh i didnt know these account are shared, its just base64 lmao

**Comment by anhwaivo** [comment]
btw thanks for the tool and stuff!
