### ISSUE TITLE
wrong installation

### ISSUE THREAD

**Issue by sanjiamca** [oureveryday/WallpaperEngineWorkshopDownloader#4]
It installs the file in the wrong place, I don't know if it's because I installed it on the d disk. For example, if the place where I installed the wallpaper engine is D:\games\Wallpaper Engine here, when I download wallpaper, it creates a folder called D:\games\wallpaper and installs it here.(engine path selection part I selected the wallpaper engine folder)

**Comment by Ali246801232** [comment]
doesnt handle folder paths with spaces unfortunately.
"D:\Games\Wallpaper Engine" will cause an issue and it'll cut it off at the space making it "D:\Games\Wallpaper"

**Comment by oureveryday** [comment]
Fixed in [1.0.1](https://github.com/oureveryday/WallpaperEngineWorkshopDownloader/releases/tag/1.0.1)
