### ISSUE TITLE
WinError 2

### ISSUE THREAD

**Issue by morcecz** [oureveryday/WallpaperEngineWorkshopDownloader#5]
Im getting "[WinError 2] The system cannot find the file specified" in CMD.
any idea why? it results in an infinite download.

**Comment by oureveryday** [comment]
Just forgot to upload some files.
Please redownload the software here: https://github.com/oureveryday/WallpaperEngineWorkshopDownloader/releases/tag/1.0.1

**Comment by morcecz** [comment]
> Just forgot to upload some files.
> Please redownload the software here: https://github.com/oureveryday/WallpaperEngineWorkshopDownloader/releases/tag/1.0.1

thanks everything works fine now
