### ISSUE TITLE
FileNotFoundError: [WinError 2]

### ISSUE THREAD

**Issue by thekat883** [oureveryday/WallpaperEngineWorkshopDownloader#7]
How to fix this?
![Безымяagasdgdsaнный](https://github.com/user-attachments/assets/e005b694-1029-41c4-aa50-24a5a3d8043c)

**Comment by oureveryday** [comment]
make sure `depotdownloadermod` folder is beside the program itself.

**Comment by thekat883** [comment]
> убедитесь, что `depotdownloadermod`папка находится рядом с самой программой.

sure
![image](https://github.com/user-attachments/assets/01a9d5ef-351f-4a95-93d7-31c19269401e)
