### ISSUE TITLE
Invaild save location

### ISSUE THREAD

**Issue by PHSalamander** [oureveryday/WallpaperEngineWorkshopDownloader#8]
But directory does  contain \projects\myprojects
![Screenshot (9)](https://github.com/user-attachments/assets/3118facc-0546-47bc-aad4-3ea7601add85)

**Comment by oureveryday** [comment]
Please select `D:\wallpaper_engine`

**Comment by PHSalamander** [comment]
> Please select `D:\wallpaper_engine`

thank you man
