### ISSUE TITLE
No download progressing

### ISSUE THREAD

**Issue by 10lalib** [oureveryday/WallpaperEngineWorkshopDownloader#9]
Followed the procedure as following:

chose the account
set the address
pasted the link and then click download. 

> https://steamcommunity.com/sharedfiles/filedetails/?id=3343374776&searchtext=

some lines gets printed in the console and then stops with nothing being downloaded as shown below:

> ----------Downloading 3343374776--------
> Connecting to Steam3... Done!
> Logging '787109690' into Steam3...
> Guard Data:
>  Done!
> Using Steam3 suggested CellID: 30
> Got 4 licenses for account!
> Got AppInfo for 431960
> Got depot key for 431960 result: OK
> Processing depot 431960
> Downloading depot manifest...Got manifest request code for 431960 8399944908627959189 result: 12418003545216029926

please help

**Comment by xxOrdulu52xx** [comment]
have this too

**Comment by oureveryday** [comment]
You should just wait for download to complete.

**Comment by 10lalib** [comment]
> You should just wait for download to complete.

I waited a good 30 mins without any progress
i will try again later today

**Comment by oureveryday** [comment]
This is fixed in new version [1.0.2](https://github.com/oureveryday/WallpaperEngineWorkshopDownloader/releases/tag/1.0.2)
